version: "3.8"

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_app
    restart: always
    ports:
      - "${PORT}:5678"
    environment:
      # PostgreSQL từ Render
      DB_TYPE: postgresdb
      DB_POSTGRESDB_URL: postgresql://thanhnhut2506:iOrjPq0AQroKDd0qgo115h8dHw19X7iV@dpg-d49n8f49c44c739gnjv0-a.singapore-postgres.render.com:5432/n8ndb_djk2?sslmode=require

      # Timezone
      GENERIC_TIMEZONE: Asia/Ho_Chi_Minh

      # Auth
      N8N_BASIC_AUTH_USER: thanhnhut2506
      N8N_BASIC_AUTH_PASSWORD: iOrjPq0AQroKDd0qgo115h8dHw19X7iV

      # Permissions
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "false"

      # Host / Port
      N8N_HOST: 0.0.0.0
      N8N_PORT: 5678
      N8N_PROTOCOL: https

      # Webhook
      WEBHOOK_URL: https://n8n-4yzg.onrender.com
